#!/bin/bash

# Test iOS Save Operation - Task 5.1
# This script provides instructions for manually testing the iOS Firebase save operation

echo "=========================================="
echo "iOS Firebase Save Operation Test - Task 5.1"
echo "=========================================="
echo ""
echo "This test verifies that daily logs are saved to Firebase from iOS."
echo ""
echo "PREREQUISITES:"
echo "1. iOS Simulator is installed (Xcode)"
echo "2. Firebase project is configured"
echo "3. User account exists for testing"
echo ""
echo "TEST STEPS:"
echo ""
echo "Step 1: Build and Run iOS App"
echo "  cd iosApp"
echo "  xcodebuild -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 15' build"
echo "  open iosApp.xcodeproj"
echo "  # Press Cmd+R to run in Xcode"
echo ""
echo "Step 2: Sign In"
echo "  - Use test account: test@example.com / password123"
echo "  - Or create a new account"
echo ""
echo "Step 3: Navigate to Daily Logging"
echo "  - Tap on 'Daily Log' tab"
echo "  - Select today's date"
echo ""
echo "Step 4: Fill in Log Data"
echo "  - Period Flow: Select 'Medium'"
echo "  - Symptoms: Select 'Cramps' and 'Headache'"
echo "  - Mood: Select 'Happy'"
echo "  - BBT: Enter '98.6'"
echo "  - Notes: Enter 'Test log from iOS'"
echo ""
echo "Step 5: Save the Log"
echo "  - Tap 'Save Daily Log' button"
echo "  - Watch for success message"
echo ""
echo "EXPECTED RESULTS:"
echo "✅ 1. 'Log saved successfully' message appears"
echo "✅ 2. Message disappears after 3 seconds"
echo "✅ 3. No error messages appear"
echo ""
echo "Step 6: Check Xcode Console Logs"
echo "  Look for these log patterns:"
echo "  - '💾 [SAVE] Starting save operation'"
echo "  - '📤 [FIRESTORE] Saving daily log to Firebase'"
echo "  - '✅ [FIRESTORE] Successfully saved daily log'"
echo "  - Document path: users/{userId}/dailyLogs/{logId}"
echo ""
echo "Step 7: Verify in Firebase Console"
echo "  1. Open https://console.firebase.google.com"
echo "  2. Select your project"
echo "  3. Go to Firestore Database"
echo "  4. Navigate to: users > {userId} > dailyLogs > {date}"
echo "  5. Verify document exists with correct fields:"
echo "     - date: (epoch days number)"
echo "     - periodFlow: 'MEDIUM'"
echo "     - symptoms: ['CRAMPS', 'HEADACHE']"
echo "     - mood: 'HAPPY'"
echo "     - bbt: 98.6"
echo "     - notes: 'Test log from iOS'"
echo "     - createdAt: (timestamp in seconds)"
echo "     - updatedAt: (timestamp in seconds)"
echo ""
echo "Step 8: Verify Data Format"
echo "  Check that the document matches Android format:"
echo "  - Field names are identical"
echo "  - Date is stored as epoch days (number)"
echo "  - Timestamps are in seconds (not milliseconds)"
echo "  - Enum values are uppercase strings"
echo ""
echo "=========================================="
echo "TROUBLESHOOTING:"
echo "=========================================="
echo ""
echo "If save fails:"
echo "1. Check internet connection"
echo "2. Verify user is authenticated (check console for userId)"
echo "3. Check Firebase security rules allow writes"
echo "4. Look for error logs in Xcode console"
echo ""
echo "If no logs appear in console:"
echo "1. Make sure you're viewing the correct target"
echo "2. Check that StructuredLogger is enabled"
echo "3. Look for NSLog output with [SAVE] or [FIRESTORE] prefix"
echo ""
echo "If document doesn't appear in Firebase:"
echo "1. Wait 5-10 seconds and refresh"
echo "2. Check you're looking at the correct user ID"
echo "3. Verify the date format (YYYY-MM-DD)"
echo "4. Check Firebase security rules"
echo ""
echo "=========================================="
echo "AUTOMATED VERIFICATION:"
echo "=========================================="
echo ""
echo "To verify programmatically, run:"
echo "  ./verify-test-readiness.sh"
echo ""
