name: Comprehensive Cross-Platform Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - unit
        - integration
        - cross-platform

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
  JAVA_VERSION: '17'

jobs:
  # Job 1: Common/Shared Module Tests
  shared-tests:
    name: Shared Module Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run shared module tests
      run: ./gradlew shared:testDebugUnitTest --continue --stacktrace
      
    - name: Upload shared test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: shared-test-results
        path: |
          shared/build/reports/tests/
          shared/build/test-results/
        retention-days: 7

  # Job 2: Android Tests
  android-tests:
    name: Android Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run Android unit tests
      run: ./gradlew androidApp:testDebugUnitTest --continue --stacktrace
      
    - name: Upload Android test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-test-results
        path: |
          androidApp/build/reports/tests/
          androidApp/build/test-results/
        retention-days: 7

  # Job 3: Cross-Platform Consistency Validation
  cross-platform-validation:
    name: Cross-Platform Consistency
    runs-on: ubuntu-latest
    needs: [shared-tests, android-tests]
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run cross-platform consistency validation
      run: ./gradlew shared:testDebugUnitTest --tests "com.eunio.healthapp.testutil.CrossPlatformConsistencyValidator" --continue --stacktrace
      
    - name: Run comprehensive test suite validation
      run: ./gradlew shared:testDebugUnitTest --tests "com.eunio.healthapp.testutil.ComprehensiveTestSuiteValidator" --continue --stacktrace
      
    - name: Upload cross-platform validation results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cross-platform-validation-results
        path: |
          shared/build/reports/tests/
          shared/build/test-results/
        retention-days: 7

  # Job 4: Test Suite Health Check
  test-suite-health:
    name: Test Suite Health Check
    runs-on: ubuntu-latest
    needs: [shared-tests, android-tests, cross-platform-validation]
    if: always()
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Make test validation script executable
      run: chmod +x ./test_suite_validation.sh
      
    - name: Run comprehensive test suite validation
      run: ./test_suite_validation.sh
      
    - name: Download all test artifacts
      uses: actions/download-artifact@v4
      with:
        path: ci-test-results/
        
    - name: Generate comprehensive test report
      run: |
        mkdir -p test-results/ci-summary
        echo "# CI/CD Test Execution Summary" > test-results/ci-summary/ci-report.md
        echo "" >> test-results/ci-summary/ci-report.md
        echo "**Generated:** $(date)" >> test-results/ci-summary/ci-report.md
        echo "" >> test-results/ci-summary/ci-report.md
        echo "## Job Results" >> test-results/ci-summary/ci-report.md
        echo "" >> test-results/ci-summary/ci-report.md
        echo "- **Shared Tests:** ${{ needs.shared-tests.result }}" >> test-results/ci-summary/ci-report.md
        echo "- **Android Tests:** ${{ needs.android-tests.result }}" >> test-results/ci-summary/ci-report.md
        echo "- **Cross-Platform Validation:** ${{ needs.cross-platform-validation.result }}" >> test-results/ci-summary/ci-report.md
        echo "" >> test-results/ci-summary/ci-report.md
        
    - name: Upload comprehensive test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: comprehensive-test-report
        path: |
          test-results/
          ci-test-results/
        retention-days: 30