name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15  # ensures Xcode and Gradle are available

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build shared Kotlin module
        run: ./gradlew :shared:build --stacktrace

      - name: Build Android app
        run: ./gradlew :androidApp:assembleDebug --stacktrace

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build iOS framework
        run: ./gradlew :shared:packForXcode

      - name: Run tests
        run: ./gradlew test --stacktrace
